
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def create_assets():
    # Create window
    window = Tk()
    window.geometry("780x480")
    window.configure(bg = "#FFFFFF")
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 480,
        width = 780,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )
    canvas.place(x = 0, y = 0)

    # Image Line
    image_line = PhotoImage(
        file=relative_to_assets("line.png"))
    line = canvas.create_image(
        511.0,
        238.0,
        image=image_line
    )

    # Image plug head 
    image_plug_head = PhotoImage(
        file=relative_to_assets("plug_head.png"))
    plug_head = canvas.create_image(
        68.0,
        239.00001525878906,
        image=image_plug_head
    )

    # Image compressor_body
    image_compressor_body = PhotoImage(
        file=relative_to_assets("compressor_body.png"))
    compressor_body = canvas.create_image(
        613.0,
        240.0,
        image=image_compressor_body
    )
    canvas.create_text(
        547.0 + 10,
        147.0,
        anchor="nw",
        text="COMPRESSOR",
        fill="#FFFFFF",
        font=("Anton\Regular 16 bold")
    )

    # compressor_button
    image_compressor_button = PhotoImage(
        file=relative_to_assets("compressor_button.png"))
    compressor_button = Button(
        image=image_compressor_button,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("compressor_button clicked"),
        relief="flat"
    )
    compressor_button.place(
        x=606.0,
        y=306.0,
        width=15.0,
        height=15.0
    )

    # Image fuzz_body
    image_fuzz_body = PhotoImage(
        file=relative_to_assets("fuzz_body.png"))
    fuzz_body = canvas.create_image(
        467.0,
        240.0,
        image=image_fuzz_body
    )
    canvas.create_text(
        404.0 + 45,
        147.0,
        anchor="nw",
        text="FUZZ",
        fill="#FFFFFF",
        font=("Anton\Regular 16 bold")
    )

    # fuzz_button
    image_fuzz_button = PhotoImage(
        file=relative_to_assets("fuzz_button.png"))
    fuzz_button = Button(
        image=image_fuzz_button,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("fuzz_button clicked"),
        relief="flat"
    )
    fuzz_button.place(
        x=460.0,
        y=306.0,
        width=15.0,
        height=15.0
    )

    # Image wah_body
    image_wah_body = PhotoImage(
        file=relative_to_assets("wah_body.png"))
    wah_body = canvas.create_image(
        325.0,
        240.0,
        image=image_wah_body
    )
    canvas.create_text(
        277.0 + 5,
        147.0,
        anchor="nw",
        text="WAH-WAH",
        fill="#FFFFFF",
        font=("Anton\Regular 16 bold")
    )

    # wah_button
    image_wah_button = PhotoImage(
        file=relative_to_assets("wah_button.png"))

    wah_button = Button(
        image=image_wah_button,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("wah_button clicked"),
        relief="flat"
    )
    wah_button.place(
        x=318.0,
        y=306.0,
        width=15.0,
        height=15.0
    )

    # Image moorer_body
    image_moorer_body = PhotoImage(
        file=relative_to_assets("moorer_body.png"))
    moorer_body = canvas.create_image(
        180.0,
        240.0,
        image=image_moorer_body
    )
    canvas.create_text(
        147.0,
        147.0,
        anchor="nw",
        text="MOORER \nREVERB",
        fill="#FFFFFF",
        font=("Anton\Regular 16 bold")
    )

    # moorer_button
    image_moorer_button = PhotoImage(
        file=relative_to_assets("moorer_button.png"))
    moorer_button = Button(
        image=image_moorer_button,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("moorer_button clicked"),
        relief="flat"
    )
    moorer_button.place(
        x=173.0,
        y=306.0,
        width=15.0,
        height=15.0
    )

    window.resizable(False, False)
    window.mainloop()

if __name__ == '__main__':
    create_assets()
